A library to manage easily a two axis, 1 button joystick
letssteam/codal-stm32 pull request #53
Opened 2022-04-27 08:45 UTC by Pascal-Flores

This library has been created in order to handle joystiks in codal, and thus I implemented the following functionnalities :
+ Creation of a joystick class
+ Methods to get the values of the vertical / horizontal axis of the joystick
+ Methods to get and set the deadzone of the joystick
+ Methods to check if the button is pressed / if the joystick is pointed in a direction (left / top / right / bottom)
+ Methods to register events for the joystick and it's button

2022-04-27 13:21 UTC, jnthbdn requested changes

2022-04-27 13:21 UTC, jnthbdn commented on inc/drivers/joystick/joystick.h
> +typedef void (*handler)();
Corriger le h minuscule
Mettre un plus explicite sur son utilisation

2022-04-27 13:21 UTC, jnthbdn commented on inc/drivers/joystick/joystick.h
> +enum JoystickAxis { Horizontal, Vertical };
Pour que ce soit parfait, on pourrait utiliser des `enum class`

2022-04-27 13:21 UTC, jnthbdn commented on inc/drivers/joystick/joystick.h
> +    Joystick(codal::STM32Pin& horizontalAxisPin, codal::STM32Pin& verticalAxisPin, codal::STM32Pin& buttonPin,
Mettre le constructeur et le destructeur en premier pour simplifier la lecture

2022-04-27 13:21 UTC, jnthbdn commented on inc/drivers/joystick/joystick.h
> +    Joystick(codal::STM32Pin& horizontalAxisPin, codal::STM32Pin& verticalAxisPin, codal::STM32Pin& buttonPin,
on peut retirer le terme `codal::` car on est déjà dans le namespace codal

2022-04-27 13:21 UTC, jnthbdn commented on inc/drivers/joystick/joystick.h
> +    codal::Button* button;
on peut retirer le terme `codal::` car on est déjà dans le namespace codal

2022-04-27 13:21 UTC, jnthbdn commented on source/drivers/joystick/joystick.cpp
> +Joystick::Joystick(codal::STM32Pin& horizontalAxisPin, codal::STM32Pin& verticalAxisPin, codal::STM32Pin& buttonPin,
on peut retirer le terme `codal::` car on est déjà dans le namespace codal (via `using namespace codal`)

2022-04-27 13:21 UTC, jnthbdn commented on source/drivers/joystick/joystick.cpp
> +    horizontalSensor = new AnalogSensor(horizontalAxisPin, 6666);
On ne peut pas garder des ID en dur, il faut trouver un moyen de les générer. @nedseb Tu connais un moyen simple ?

2022-04-27 13:21 UTC, jnthbdn commented on source/drivers/joystick/joystick.cpp
> +    return;
Inutile de return à la fin

2022-04-27 13:21 UTC, jnthbdn commented on source/drivers/joystick/joystick.cpp
> +        axisValue = (axisValue - 512 + deadzone) * (100 - 0) / (1023 - 512 + deadzone) + 1;
Peut-être extraire le calcul dans une fonction afin de comprendre ce qu'il fait directement à la lecture

2022-04-27 13:21 UTC, jnthbdn commented on source/drivers/joystick/joystick.cpp
> +        axisValue = (axisValue - 512 + deadzone) * (100 - 0) / (1023 - 512 + deadzone) + 1;
Attention au "magic value" -100 et 100. Peut être utiliser un `constexpr` afin de stocker ces valeurs et rendre la sortie paramétrable.

2022-04-27 13:21 UTC, jnthbdn commented on source/drivers/joystick/joystick.cpp
> +    switch (direction) {
Peut retirer le switch qui complique un peu la lecture du code.

2022-04-27 13:21 UTC, jnthbdn commented on source/drivers/joystick/joystick.cpp
> +bool Joystick::isButtonPressed()
On pourrait mettre cette toutes petit fonction directement dans le fichier .h

2022-04-27 13:21 UTC, jnthbdn commented on source/drivers/joystick/joystick.cpp
> +    else
Else qui fait juste un return n'est pas très utile

2022-04-27 13:48 UTC, Pascal-Flores commented on inc/drivers/joystick/joystick.h
> +typedef void (*handler)();
handler rennomé en JoystickUserEvent

2024-05-13 09:26 UTC, nedseb approved these changes

2024-05-13 09:26 UTC, merged