Remplacement define par printRadix et création des utils pour registerBit
letssteam/codal-stm32 pull request #90
Opened 2024-01-24 10:54 UTC by Charly-sketch

Je suis pas sur pour l'emplacement de mes utils et il y a d'autres register bit dans : 
- /workspaces/codal-letssteam/codal/libraries/codal-stm32/source/drivers/MCP23009-E/mcp23009-e.cpp
- /workspaces/codal-letssteam/codal/libraries/codal-stm32/source/drivers/WSEN-PADS/WSEN-PADS.cpp

mais il ne fonctionne pas pareille que ceux que j'ai factoriser

2024-01-24 11:41 UTC, jnthbdn requested changes

2024-01-24 11:41 UTC, jnthbdn commented on inc/drivers/lcd_utils.h
> +enum class PrintRadix : uint8_t { HEX = 16, DEC = 10, OCT = 8, BIN = 2 };
Je pense qu'il faudrait le mettre dans le namespace `codal` afin d'être cohérent avec le reste du code.

2024-01-24 11:41 UTC, jnthbdn commented on inc/drivers/rgb_lcd.h
> +  size_t print(unsigned char, int = static_cast<int>(PrintRadix::DEC));
Je ne suis pas hyper fan du `static_cast`. Autant utiliser notre type `PrintRadix`, même si cela demande de faire des modifications MakeCode.

2024-01-24 11:41 UTC, jnthbdn commented on source/drivers/registerBit_utils.cpp
Ce serait mieux d'avoir un fichier `.h` au lieu du `.cpp` car on se retrouve à faire des `include` de fichier `.cpp` sinon, ce n'est pas super propre.
Ensuite je pense que le placer dans le dossier `inc` sera plus simple pour s'y retrouver.

2024-01-24 11:41 UTC, jnthbdn commented on inc/drivers/lcd_utils.h
Je pense que le placer dans le dossier `inc` sera plus simple pour s'y retrouver.

2024-01-24 11:41 UTC, jnthbdn commented on source/drivers/ISM330DL/ism330dl.cpp
> +#include "../registerBit_utils.cpp"
cf. commentaire du fichier util lui-même

2024-01-24 11:41 UTC, jnthbdn commented on source/drivers/LIS2MDL/lis2mdl.cpp
> +#include "../registerBit_utils.cpp"
cf. commentaire du fichier util lui-même

2024-01-24 11:43 UTC, jnthbdn commented
Super !
Par contre penses à bien tester la compilation des tes modifications avec la/les targets. Ca évite d'avoir à attendre que le CI termine (ce qui peut prendre du temps ^^).

Visiblement il y a une erreur de namespace (`lcd.print(10, codal::PrintRadix::DEC);`), mais qui est en lien avec un commentaire de review.

2024-01-24 18:11 UTC, jnthbdn requested changes

2024-01-24 18:11 UTC, jnthbdn commented on inc/drivers/i2c_lcd.h
> +    #include "lcd_utils.h"
il vaut mieux mettre l'include en haut du fichier

2024-01-24 18:11 UTC, jnthbdn commented on inc/drivers/registerBit_utils.h
> +#ifndef REGISTERBIT_UTILS_H
😵 Arf ! Encore du C...
Pareil que pour le fichier d'avant ^^

2024-01-24 18:11 UTC, jnthbdn commented on inc/drivers/rgb_lcd.h
> +  #include "lcd_utils.h"
Idem que précédemment, il vaut mieux le mettre en haut du fichier

2024-01-24 18:11 UTC, jnthbdn commented on inc/drivers/rgb_lcd.h
> +  // size_t print(const char[]);
Une fois que tout fonctionne tu pourra supprimer ces lignes commentées.

2024-01-24 18:11 UTC, jnthbdn commented on inc/drivers/lcd_utils.h
> +#ifndef LCD_UTILS_H
😵 Arf ! Du C...
Pour éviter d'avoir à gérer des #ifndef avec des #define et cie. Tu peux tout remplacer par #pragma one cela à exactement le même effet, mais en plus court et plus lisible ^^

2024-01-24 18:11 UTC, jnthbdn commented on inc/drivers/i2c_lcd.h
> +    #include "lcd_utils.h"
et oublie ce que j'ai dis dans la review précédente, que le type se retrouve dans le namespace est un peu con... on ne l'a jamais fait dans les autre fichiers... désolé...

2024-01-25 12:58 UTC, jnthbdn requested changes
Deplace les fichier utils dans le dossier `inc` est ce sera parfait. Une fois la PR validée, il faudra tester que rien ne soit cassé sur MakeCode

2024-01-26 16:02 UTC, jnthbdn approved these changes

2024-05-13 09:17 UTC, nedseb approved these changes

2024-05-13 09:18 UTC, merged